version: "3"

services:
  web:
   depends_on:
    - db
   image: wordpress:latest 
   restart: always
   ports:
    - "8000:80"
   environment:
     WORDPRESS_DB_HOST: db:3306
     WORDPRESS_DB_USER: wordpress
     WORDPRESS_DB_PASSWORD: wordpress

  db:
   image: mysql/mysql-server:latest
   restart: always
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: wordpress
     MYSQL_USER: wordpress
     MYSQL_PASSWORD: wordpress

   volumes:
     - db_data:/var/lib/mysql

volumes:
  db_data:     

